apiVersion: v1
kind: Service
metadata:
  name: backstage
spec:
  type: NodePort
  selector:
    janus-idp.io/app:  # placeholder for 'backstage-<cr-name>'
  ports:
    - name: http
      port: 80
      targetPort: http